### ISSUE TITLE
After install the icon disappears

### ISSUE THREAD

**Issue by johnbrett** [cymen/show-me-the-react#3]
After I installed the show-me-the-react extension, the icon disappeared, so I have no idea how to interact with it - any ideas on how to get it to return?

**Comment by frnk94** [comment]
Its only appear on page that contains react try to go on instagram its should appear on the address bar

**Comment by johnbrett** [comment]
Ah I was testing it on a site that use server-side react rendering. Thanks
for getting back to me.
