### ISSUE TITLE
Simliar extension

### ISSUE THREAD

**Issue by cymen** [cymen/show-me-the-react#5]
![screen shot 2015-07-27 at 1 17 56 pm](https://cloud.githubusercontent.com/assets/121034/8916664/f0b553b6-3461-11e5-8ac2-7964de08d809.png)

**Comment by cymen** [comment]
@kentcdodds Ah, I didn't realize it was yours. You might consider updating the description to mention the highlighting capability and adding a screenshot of highlighting. For me, that was the biggest realization: communication really matters and is important. If nobody knows what your extension does, are they going to take the time to install and try it?

I am moving this discussion here to this new issue -- the other one is focused on improvements to the extension and this is pretty far off topic.

**Comment by kentcdodds** [comment]
Right, sounds good. I'll go update the readme now.

**Comment by cymen** [comment]
:+1:

**Comment by kentcdodds** [comment]
Feel free to close this issue :-)

**Comment by cymen** [comment]
Cool, will do!
